### ISSUE TITLE
ETABS_Toolkit: Bar connectivity is flipped after the API call

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/ETABS_Toolkit#101]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Closing this as superseeded by https://github.com/BHoM/ETABS_Toolkit/issues/232
Keeping new issue as more information is kept in there.
