### ISSUE TITLE
ETABS_Toolkit: Update properties behavior

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/ETABS_Toolkit#102]
It is often advantageous to use existing section properties if they are already loaded in ETABS, especially if the section was not output correctly from Revit (as many are coming in as FreeForm at the moment). Can we add a toggle to the adapter config to specify this behavior?

**Comment by IsakNaslundBh** [comment]
Will be resolved via https://github.com/BHoM/BHoM_Adapter/issues/204
