### ISSUE TITLE
ETABS Toolkit: Bar push fails if filled tube section defined in the model

### ISSUE THREAD

**Issue by dlamianski** [BHoM/ETABS_Toolkit#160]
Bar push fails if filled tube section defined in the model.

Error description:

> 1. This component failed to run properly. Are you sure you have the correct type of inputs?
> Check their description for more details. Here is the error provided by the method:
> Section convertion for the type: FilledTube is not implemented in ETABS adapter

Test script has been added to Magellan. 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Etabs_Toolkit-Issue160-BarPushFailure/Etabs%20Toolkit-Issue%20160-Test%20Script.gh?csf=1&e=Q8sN7Z

Script is successful in a blank model, but fails to work when filled tube section are defined.

**Comment by JosefTaylor** [comment]
This is also true when Double Angles are defined. It's because pushing starts off by pulling all available sections, and those not-implemented sections cause it to fail. I believe we can return a null section in the pull sections, and downgrade the error message to a warning.

**Comment by IsakNaslundBh** [comment]
@JosefTaylor I do agree. Actually raised a new issue for this two days ago after same problem showing up in London.

https://github.com/BHoM/ETABS_Toolkit/issues/192

Also seem we have come to the same conclusion, no exception throwing, but instead recording errors. Could maybe close this and replace with the superseeded? But happy to leave that to you.
