### ISSUE TITLE
Mesh Force Query from ETABS fails to obtain results

### ISSUE THREAD

**Issue by dlamianski** [BHoM/ETABS_Toolkit#165]
Based on testing of the BHoM ETABS Toolkit code, it seems like and additional "ret = model.Results.Setup.SetCaseSelectedForOutput(loadcaseIds[i])" inside a loop might needs to be added to the "GetMeshForce" method. Additionally, the "StepNum[j]" variable seems to throw an exception in the definition setting of "pf" the length of the StepNum[j] array is not always equal to the length of the results arrays (F11, F22, etc.). 

![GitHub Issue Mesh Forces](https://user-images.githubusercontent.com/48366441/56381468-ebea1300-61e2-11e9-94a6-b7b7af5e4db3.png)

![GitHub Issue Mesh Forces2](https://user-images.githubusercontent.com/48366441/56381534-2489ec80-61e3-11e9-954d-32dddf8e0075.png)

**Comment by IsakNaslundBh** [comment]
@dlamianski can you check if this has been fixed by https://github.com/BHoM/ETABS_Toolkit/pull/230

**Comment by dlamianski** [comment]
See below. Ran it after the latest BHoM install and am still running into the same issue.

![image](https://user-images.githubusercontent.com/48366441/71097941-e16f8700-217e-11ea-8cf9-548af5d11fb6.png)

**Comment by dlamianski** [comment]
Reinstalled from the latest alpha release, seems to be working properly!

![image](https://user-images.githubusercontent.com/48366441/71098920-73c45a80-2180-11ea-989d-0dca2cefd41b.png)

**Comment by dlamianski** [comment]
Closed.
