### ISSUE TITLE
ETABS_Toolkit : Pull Grids

### ISSUE THREAD

**Issue by nirbhay93** [BHoM/ETABS_Toolkit#167]
With reference to issue: https://github.com/BHoM/ETABS_Toolkit/issues/69
Feature also required to query Levels/Storeys and Grids.

**Comment by nirbhay93** [comment]
I'm able to query Levels in the new version. Please confirm about the Grids if it is solved.

**Comment by nirbhay93** [comment]
I'm able to query Levels in the new version. Please confirm about the Grids.

**Comment by IsakNaslundBh** [comment]
Levels implemented, Grids outstanding for Read.
