### ISSUE TITLE
ETABS_Toolkit : Feature : Framings and Panels with Storey Data

### ISSUE THREAD

**Issue by nirbhay93** [BHoM/ETABS_Toolkit#168]
Feature required for framings and panels to be associated with their respective storey data.

**Comment by IsakNaslundBh** [comment]
@nirbhay93 I assume this relates to pulled bars and panels to contain storey information?

**Comment by nirbhay93** [comment]
> @nirbhay93 I assume this relates to pulled bars and panels to contain storey information?

Yes. :-)

**Comment by rwemay** [comment]
Would be good to solve this for other platforms too, so that there are common engine methods for extracting/linking storey/grid/reference information.

**Comment by IsakNaslundBh** [comment]
Closed as of https://github.com/BHoM/ETABS_Toolkit/pull/262
