### ISSUE TITLE
Etabs_Toolkit: Build different dlls for different versions of Etabs

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/ETABS_Toolkit#189]
#### Description:

The returning dlls of the adapter for etabs need to have different names depending on version of Etabs.

Example:

`Etabs2016_Adapter`
`Etabs2016_Engine`

Also need to investigate if the class name need to be changed as well.

**Comment by epignatelli** [comment]
From the Sprint Closure call - Moved this Release, since it is a release issue. @alelom to act on it.

**Comment by alelom** [comment]
Realised there is a "multiplication" problem:
   Adapter 
   ![image](https://user-images.githubusercontent.com/6352844/64876108-5c884500-d646-11e9-9a71-161f61f62aa5.png)

   any method
   ![image](https://user-images.githubusercontent.com/6352844/64876168-79247d00-d646-11e9-9f4a-92a1169b29af.png)

raising discussion @IsakNaslundBh @epignatelli @adecler @epignatelli @al-fisher @rwemay 

Potential workarounds:
1. Keep the multiplied methods, but work on the BH.Engine.Reflection.ToText() method to expose a suffix "_2016", "_2017", etc. to the methods
2. Officially support only one version at a time, leaving the option of which one be available at install time
3. any other idea/thought?

**Comment by JosefTaylor** [comment]
I’d be happy to support only one version at a time, chosen at install. Especially for the time being.


Josef Taylor, PE
Senior Engineer
BuroHappold Engineering | Structures
T: +1 212 616 0325
www.burohappold.com<http://www.burohappold.com/>   |  @burohappold<twitter.com/burohappold>

**Comment by alelom** [comment]
hey @JosefTaylor, would you mind moving your comment in the discussion PR linked above? So we can keep the issue clean. Thanks!
