### ISSUE TITLE
ETABS_Toolkit: Support ETABSv18

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/ETABS_Toolkit#221]
#### Description:

ETABSv18 uses a new .Net framework and future versions will finally stop changing the name of their API dll every time. hopefully we can reference .NET frameworks in the same way we control which name to use.

**Comment by IsakNaslundBh** [comment]
Putting in Prio 1 as PR currently open. This will need to be closed out swiftly to make sure the adapter refactoring in https://github.com/BHoM/ETABS_Toolkit/issues/237 can be worked through in time

**Comment by IsakNaslundBh** [comment]
Parking this until ETABS 18 can be tested.
