### ISSUE TITLE
ETABS_Toolkit: Width & Height missing in SectionProperty of Frames in BuroHappold_BHoM_v2.4.beta.1

### ISSUE THREAD

**Issue by nirbhay93** [BHoM/ETABS_Toolkit#229]
![New_BHoM_Issue](https://user-images.githubusercontent.com/33544613/69224999-82c8e480-0ba3-11ea-8bac-04ff928448c9.jpg)

#### Description:
Width and Height properties are missing in SectionProperty of Frames in BuroHappold_BHoM_v2.4.beta.1

**Comment by IsakNaslundBh** [comment]
@nirbhay93 can you check what section type you are getting out? And also, what section you have in ETABS?

Think you are handed back a ExplicitSection which does not have any heights/widths etc. This is the general fallback case when the read for the section is not yet implemented. It should be giving a warning stating this on the pull though.

**Comment by nirbhay93** [comment]
It's a simple rectangular concrete section with defined width and height in section properties; and there was no warning after the pull.

**Comment by IsakNaslundBh** [comment]
@nirbhay93 as this seem to be working in current alpha, are you fine with closing this issue?

**Comment by nirbhay93** [comment]
Yup.
