### ISSUE TITLE
ETABS_Toolkit: ETABS AddByPoint Sometimes Flips Bars

### ISSUE THREAD

**Issue by enarhi** [BHoM/ETABS_Toolkit#232]
#### Description:
If bars run right to left or top to bottom they appear to be automatically flipped upon creation. We need a way to manage this or modify it for following properties for things like releases.

#### How to replicate:
Create a bar that is right to left (ie starts at 10,0,0 and ends at 0,0,0) or top to bottom (0,10,0 to 0,0,0) with a release on one side, and the release is on the opposite side when created in ETABS. I and J joints are also flipped accordingly.

#### Expected behaviour:
Bar directionality maintained and releases etc on the correct side.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Issue232-EtabsFlippingBars?csf=1&e=pb8MNB

**Comment by enarhi** [comment]
Bars pushed to ETABS with direction on left, same bars then pulled from ETABS with direction on right. L-R takes precedent, bottom to top is enforced if bar is in the y direction.

![image](https://user-images.githubusercontent.com/6752345/69743764-d97a7500-10f3-11ea-98b3-7e7109291932.png)

![image](https://user-images.githubusercontent.com/6752345/69743987-35dd9480-10f4-11ea-988a-7c5afe05ed38.png)

**Comment by IsakNaslundBh** [comment]
Have seen the same. Added a test script to the description as well. Snip from pulled bars, initial bars are all pointing outwards:

![image](https://user-images.githubusercontent.com/22005920/70613804-8cc18e80-1c09-11ea-8a81-abc6c5f2d3a0.png)

Seems like Z is checked first, then X then finally Y.
