### ISSUE TITLE
Etabs_Toolkit: Add support for local axis and projected for load push/pull

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/ETABS_Toolkit#265]
#### Description:

Currently only global non-projected supported. Local and global projected should be supported as well for all load types (where applicable).

**Comment by JosefTaylor** [comment]
Good catch on the issue name Kalle!

**Comment by IsakNaslundBh** [comment]
haha, woops!

**Comment by kThorsager** [comment]
I had some hopes about Isak's professionalism and ambitions about this toolkit
