### ISSUE TITLE
Modify methods must return the same type as their first parameter

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/ETABS_Toolkit#267]
- [ ] Modify/Upgrade.cs at 40:22
 - [ ] Modify/Upgrade.cs at 52:22

Documentation is also needed for this file but is not required in this milestone so not captured here. Please request if you would like to see full documentation issues as well.

**Comment by IsakNaslundBh** [comment]
hmm, these where done before the versioning toolkit was in place. If we had had that at the point this methods would not even be needed. Could potentially move these to the compute instead though if that would be enough to fit compliance.

**Comment by FraserGreenroyd** [comment]
Moving to compute would resolve this particular compliance issue, yes. They would be subject to compliance of Compute files but that can be run at PR time to double check.
