### ISSUE TITLE
ETABS_Toolkit: Level with elevation 0 doesn't push, returns irrelevant error.

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/ETABS_Toolkit#313]
#### Description:
Attempting to push a list of levels including one at elevation = 0 fails for all levels, the push returns the error 'can only push levels to an empty model' instead of 'could not push level with elevation 0' so it's very difficult to troubleshoot.

#### Steps to reproduce:
attempt to push a list of levels, one of which is at elevation 0.

#### Expected behaviour:
preferably handle levels with elevation =  0 by renaming the base level or otherwise dealing with it automatically. Alternately, throw a useful error letting the user know to cull the 0th level.

**Comment by kThorsager** [comment]
They've expanded the functionality in ETABS17 onvards, so should be solvable now, (and can add levels to an existing model)
