### ISSUE TITLE
ETABS_Toolkit: Change namespace of oM and Engine

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/ETABS_Toolkit#318]
#### Description

All obejcts in ETABS_oM should be in `BH.oM.Adapters.ETABS` namespace
All obejcts in ETABS_Engine should be in `BH.Engine.Adapters.ETABS` namespace

Versioning should be applied to make sure functions correctly.

**Comment by kThorsager** [comment]
So for clarification,
ETABS_oM:

Can `BH.oM.Adapters.ETABS.Elements` remain as it's a sub namespace?

And should `BH.oM.Structure.Loads.MassSource` `BH.oM.Structure.Loads.ModalCase`remain in ETABS or get sent to Structure_oM?

**Comment by IsakNaslundBh** [comment]
Good shout.

> Can BH.oM.Adapters.ETABS.Elements remain as it's a sub namespace?

Yes, that is fine

> And should `BH.oM.Structure.Loads.MassSource` `BH.oM.Structure.Loads.ModalCaseremain` in ETABS or get sent to Structure_oM?

Lets leave them as they are. Idea for them when added was for them to get migrated at one point. Do not need to do this in this PR.
