### ISSUE TITLE
Command "ClearResults" does not unlock model

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/ETABS_Toolkit#350]
#### Description:

Currently the command `ClearResults` deletes the results successfully, but the model remains locked. This is a condition which generally never occurs in normal use, so would be confusing to the user. Automated workflows would also fail to make changes, unless another command unlocks the model.

#### Expected behaviour:

When `ClearResults` is executed, it should also unlock the model.

**Comment by junjieim** [comment]
Hi guys. Any update for this issue?

**Comment by FraserGreenroyd** [comment]
Hi @junjieim there isn't currently any plans in the backlog on tackling this issue, but I'll reach out to @peterjamesnugent and see if we can put it on the radar soon if it's causing a larger issue than @JosefTaylor describes?

**Comment by junjieim** [comment]
Not a bug issue. But have to jump out of the grasshopper interface to click the unlock button in Etabs.

I simplily searched the `DeleteResults` and found it is different code between etabs and sap2000. Hope it should help.
![image](https://github.com/BHoM/ETABS_Toolkit/assets/48527686/97969b22-4733-474f-b145-608b46c9a6ab)

Thank you.
