### ISSUE TITLE
Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/ETABS_Toolkit#355]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Create\Bar.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Create\Link.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Create\Load.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Create\Loadcase.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Create\Node.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Create\Panel.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Create\SectionProperty.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Create\SurfaceProperty.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\Bar.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\Link.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\Load.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\Material.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\Mesh.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\Node.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\Panel.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\SectionProperty.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\SurfaceProperty.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Read\Results\Result.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Update\Bar.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Update\Node.cs

 - [ ] ETABS_Toolkit\Etabs_Adapter\CRUD\Update\Panel.cs

 - [ ] ETABS_Toolkit\ETABS_Engine\Compute\UpgradeVersion.cs

 - [ ] ETABS_Toolkit\ETABS_Engine\Modify\SetDiaphragm.cs

 - [ ] ETABS_Toolkit\ETABS_Engine\Modify\SetPier.cs

 - [ ] ETABS_Toolkit\ETABS_Engine\Modify\SetShellType.cs

 - [ ] ETABS_Toolkit\ETABS_Engine\Modify\SetSpandrel.cs

 - [ ] ETABS_Toolkit\ETABS_Engine\Query\Diaphragm.cs

 - [ ] ETABS_Toolkit\ETABS_Engine\Query\DiaphragmType.cs

 - [ ] ETABS_Toolkit\ETABS_Engine\Query\Pier.cs

 - [ ] ETABS_Toolkit\ETABS_Engine\Query\Spandrel.cs

</p>
</details>

**Comment by IsakNaslundBh** [comment]
Not fully closed out. Reopening
