### ISSUE TITLE
have some errors when compiling Etabs_toolkit

### ISSUE THREAD

**Issue by yuexian027** [BHoM/ETABS_Toolkit#364]
I have successfully compile the following solution: BHOM, BHOM_ADAPTER, BHOMEngine, BHOM_UI and also Grasshopper and rhino toolkit. However, there are still some errors when I build the Etabs toolkit as shown in the snapshot attached. Could you let me know what should I do to solve this problem? Thanks!
![image](https://user-images.githubusercontent.com/70185872/101118739-4f3ed980-35af-11eb-882d-f21dda9259e9.png)

**Comment by JosefTaylor** [comment]
Hi Yuexian, have you tried using our installer? It's quite handy at sorting out all the dependencies, and you can build new code on top of it. it's available at [BHoM.xyz](https://bhom.xyz/).
If that doesn't work, or if you want to build from code anyway, you can often get support in our public [Slack workspace](https://join.slack.com/t/bhom/shared_invite/enQtNTQzNjkyNzIzMjM1LWY0NzdlMGEzMjQ2YTk3M2U2YTRlODZiMjZiN2E1MzY1YmRiYTJmNjA2ODkzYzBmNmM1NzY3Y2FkN2MzNGM4ZTI):

**Comment by JosefTaylor** [comment]
I suspect the issue here is either with local paths (in which case it's our fault) or perhaps with NuGet- try refreshing/managing NuGet packages

**Comment by yuexian027** [comment]
Hi Josef,
Thanks for your reply. I have already tried to restore the NuGet packages,
but it does not help. Besides, I have downloaded the installer, but I do
not quite understand what you mean by building new code on top of it?  I
have downloaded the installer and for example when I open grasshopper, the
BHOM category is shown in the toolbar and the adapter can work well with
Etabs. Could you explain more about how to build new code on top of this
installer?  The reason why I open the source code is to try to understand
how the adapter works.
Thank you again!

Yue
