### ISSUE TITLE
ETABS_Engine.dll is not capitalised in the same way as other ETABS DLLs

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/ETABS_Toolkit#367]
![image](https://user-images.githubusercontent.com/18049174/102211043-e7e82a00-3eca-11eb-926a-7de75d1ec37c.png)

ETABS_oM and ETABS_Engine DLLs are not capitalised the same way. It appears that the full capitalisation is correct based on the adapters and the repo name, so probably best to change Etabs_Engine to ETABS_Engine - but if that is not correct then please fix the others instead 😄

**Comment by IsakLarbornBH** [comment]
![image](https://user-images.githubusercontent.com/72074998/102242742-4ffe3680-3ef2-11eb-8e04-2a9bf1c4a57b.png)

This is why. I'd submit a PR, but I'm not experienced enough to know if changing this might have any other consequences that need to be dealt with.

**Comment by IsakNaslundBh** [comment]
That is it @IsakLarbornBH . Would not make this change this week though (even though I think it is _probably_ safe. 

But lets target to get it resolved early after 4.0 is out of the way.

**Comment by FraserGreenroyd** [comment]
That is indeed why @IsakLarbornBH - I'd say submit a PR if you're up for it and then it's down to your reviewers to help work out the consequences, @IsakNaslundBh will be able to guide you :smile:

From a CI/CD perspective - no impact on our side, so it'll only be potentially impacting something structures side.
