### ISSUE TITLE
Etabs_Toolkit: Ensure Results consistency with other toolkits

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/ETABS_Toolkit#42]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
https://github.com/BHoM/Robot_Toolkit/issues/56
https://github.com/BHoM/GSA_Toolkit/issues/28

As both of these related issues, which were part of the historic reference for this issue, have been closed, I think it is safe to close this issue as well. @IsakNaslundBh please feel free to reopen if you disagree 😄
