### ISSUE TITLE
Levels are not pushing to a new model and an error is incorrectly raised 

### ISSUE THREAD

**Issue by sonyaqaderi** [BHoM/ETABS_Toolkit#435]
#### Description:

When pushing several object `type`s such as `Levels`, `Floors` and `Walls` - the `Levels` do not push and return an error for not pushing to a new model (despite the model being new).

When pushed independently the `Levels` push fine.

#### Steps to reproduce:

See test script.

#### Expected behaviour:

Levels to push without error.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/ETABS_Toolkit/%23435-LevelsNotPushingWithOtherObjects?csf=1&web=1&e=vzabMA

**Comment by peterjamesnugent** [comment]
See here: https://github.com/BHoM/BHoM_Adapter/issues/390
