### ISSUE TITLE
ETABS_Toolkit : Remove unnecessary load filtering

### ISSUE THREAD

**Issue by MartinHenriksen** [BHoM/ETABS_Toolkit#44]
on the first PR of push/pull loads and combinations the ReadLoad-method reads all loadcases, reads all loads then filters the loads by type to return only the requested load types... this is not optimal - consider refactoring

**Comment by IsakNaslundBh** [comment]
@MartinHenriksen is this still an issue?

**Comment by IsakNaslundBh** [comment]
This should have been resolved with changes on the adapters
