### ISSUE TITLE
Wind LoadCase cannot input to ETABS17

### ISSUE THREAD

**Issue by samloo1997** [BHoM/ETABS_Toolkit#450]
#### Description:
Enum LoadNature for Wind converts to Gravity Load instead of Wind Load in ETABS 2017
![image](https://github.com/BHoM/BHoM_Engine/assets/139096240/ca21f163-0a4d-4015-8bd7-62b1ed11f6a8)

#### Steps to reproduce:
1. Connect CreateENUM LoadNature: Wind to CreateBHoM Loadcase 
2. Connect the Loadcase to Push function with ETABS17 Adaptor and AdapterDefault as pushtype
![image](https://github.com/BHoM/BHoM_Engine/assets/139096240/69e2d9f7-5ae6-4abc-a03c-4030b5be53d1)

#### Expected behaviour:
Type in Load Patterns should be Wind instead of Dead

#### Test file(s):
[failedloadcase_wind.zip](https://github.com/BHoM/BHoM_Engine/files/14930558/failedloadcase_wind.zip)

**Comment by IsakNaslundBh** [comment]
Thanks for raising @samloo1997 .

You are right, was a typo in the convert of the load nature enum in the adapter. Will raise a PR for this, if you are able to help review that would be great!

Thanks
