### ISSUE TITLE
ETABS_Toolkit : additional results to read

### ISSUE THREAD

**Issue by MartinHenriksen** [BHoM/ETABS_Toolkit#50]
not all results are supported - still missing:

- ### Node results
- [ ] Joint acceleration

- [ ]  Joint velocity

- ### Bar results
- [ ] frame deformation

- [ ]  frame strain

- [ ]  frame stress

- ### Panel results
- [ ]  area stress
- ### Global results
- [ ]  global reactions
- ### Pier and Spandrel results
- [ ]  pier and spandrel stresses
- [x] pierForce
- [ ] Spandrel force

**Comment by IsakNaslundBh** [comment]
Closed as superseded by separate split up issues
