### ISSUE TITLE
Rigid links unique ID does not match

### ISSUE THREAD

**Issue by ncbrown2** [BHoM/ETABS_Toolkit#55]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Think this has been resolved since https://github.com/BHoM/ETABS_Toolkit/pull/210

Please feel free to re-open if this is not the case and the issue presists.
