### ISSUE TITLE
Error when pulling load combinations

### ISSUE THREAD

**Issue by ncbrown2** [BHoM/ETABS_Toolkit#56]
When pulling loads using a test script, Grasshopper shows a "1. Solution exception:Value cannot be null." error. This component attempts to run GetLoadCombination, but model.RespCombo.getCaseList() does not properly return the correct arrays. Thus caseNames is still null, which throws an exception when going into the loop

**Comment by IsakNaslundBh** [comment]
Will close this as old and no recent reports on problems with pulling combinations. Please feel free to re-open if I am in the wrong.
