### ISSUE TITLE
ETABS_Toolkit: Pulling and Pushing missing loads

### ISSUE THREAD

**Issue by al-fisher** [BHoM/ETABS_Toolkit#65]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Loads still not able to be pushed/pulled needed to be added as priority:

- BarTemprature
- BarPointLoad
- AreaTemprature

Also, need to be able to pull varying distributed loads. This might require a slight tweak to pulling distributed loads in general.
