### ISSUE TITLE
ETABS_Toolkit: Test script Push all objects types implemented

### ISSUE THREAD

**Issue by al-fisher** [BHoM/ETABS_Toolkit#66]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
To be handled with general Push-Pull test framework in Testing_Toolkit and with CI

**Comment by FraserGreenroyd** [comment]
Test scripts for ETABS have been set up and used by @IsakNaslundBh and others for end-of-milestone testing and are quite robust, so I'm closing this issue as completed 😄
