### ISSUE TITLE
Etabs_Toolkit: Pushing Panels

### ISSUE THREAD

**Issue by Droidx1** [BHoM/ETABS_Toolkit#74]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
I believe the worst part of this has been solved in https://github.com/BHoM/ETABS_Toolkit/pull/100

Still issues with warnings not raised for failing wall panels, and reason to why it is failing
