### ISSUE TITLE
ETABS_Toolkit: Push Nodal Loads not working

### ISSUE THREAD

**Issue by emidio-piermarini** [BHoM/ETABS_Toolkit#84]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Think this was fixed by https://github.com/BHoM/ETABS_Toolkit/pull/83
@emidio-piermarini ?

**Comment by IsakNaslundBh** [comment]
Closing this as should have been resolved since #83 . @emidio-piermarini feel free to re-open if you still have issues with this
