### ISSUE TITLE
ETABS_Toolkit:  Create Always Returns True

### ISSUE THREAD

**Issue by emidio-piermarini** [BHoM/ETABS_Toolkit#85]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by JosefTaylor** [comment]
This is now preferred behavior- return true and spit an error/warning.
